# This is a title
## This is a subtitle
These are notes:
- Note 1
- Note 2

In [1]:
print ("hello world")

hello world

In [3]:
# Task

# Task:
1. Download csv files
2. Load into this notebook
3. Clean the csvs
4. Output clean files

Pandas Demo

In [4]:
import pandas as pd

In [10]:
data = pd.read_csv("Data/03_Library SystemCustomers.csv")

In [12]:
data.head

<bound method NDFrame.head of    Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted>

In [13]:
customers = data
customers.head

<bound method NDFrame.head of    Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted>

In [14]:
del data

In [17]:
customers = customers.dropna()
customers.head

<bound method NDFrame.head of    Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted>

In [58]:
customers.to_csv("Data/03_Library SystemCustomers_clean.csv, index=False")

In [43]:
books = pd.read_csv("Data/03_Library Systembook.csv")

In [44]:
books.head

<bound method NDFrame.head of       Id                                     Books Book checkout  \
0    1.0                       Catcher in the Rye   "20/02/2023"
1    2.0          Lord of the rings the two towers  "24/03/2023"
2    3.0  Lord of the rings the return of the kind  "29/03/2023"
3    4.0                                The hobbit  "02/04/2023"
4    5.0                                     Dune   "02/04/2023"
..   ...                                       ...           ...
109  NaN                                       NaN           NaN
110  NaN                                       NaN           NaN
111  NaN                                       NaN           NaN
112  NaN                                       NaN           NaN
113  NaN                                       NaN           NaN

    Book Returned Days allowed to borrow  Customer ID
0      25/02/2023                2 weeks          1.0
1      21/03/2023                2 weeks          2.0
2      25/03/2023                2 weeks          3.0
3      25/03/2023                2 weeks          4.0
4      25/03/2023                2 weeks          5.0
..            ...                    ...          ...
109           NaN                    NaN          NaN
110           NaN                    NaN          NaN
111           NaN                    NaN          NaN
112           NaN                    NaN          NaN
113           NaN                    NaN          NaN

[114 rows x 6 columns]>

In [45]:
books = books.dropna()
books.head

<bound method NDFrame.head of       Id                                     Books Book checkout  \
0    1.0                       Catcher in the Rye   "20/02/2023"
1    2.0          Lord of the rings the two towers  "24/03/2023"
2    3.0  Lord of the rings the return of the kind  "29/03/2023"
3    4.0                                The hobbit  "02/04/2023"
4    5.0                                     Dune   "02/04/2023"
5    6.0                              Little Women  "02/04/2023"
6    7.0                                        IT  "10/04/2063"
7    8.0                                   Misery   "15/04/2023"
8    9.0                                  Catch 22  "15/04/2023"
9   10.0                              Animal Farm   "20/04/2023"
10  11.0                                      1984  "23/04/2023"
11  12.0                              Little Women  "02/04/2023"
12  13.0                              East of Eden  "30/04/2023"
13  14.0                   America Is in the Heart  "01/05/2023"
14  15.0                         Wuthering Heights  "01/05/2023"
15  16.0                                Dark Tales  "15/05/2023"
16  17.0                        The Bloody Chamber  "32/05/2023"
17  18.0                            Les Miserables  "03/06/2023"
18  19.0                                   Dracula  "10/06/2023"
19  20.0                              Frankenstein  "01/06/2023"

   Book Returned Days allowed to borrow  Customer ID
0     25/02/2023                2 weeks          1.0
1     21/03/2023                2 weeks          2.0
2     25/03/2023                2 weeks          3.0
3     25/03/2023                2 weeks          4.0
4     25/03/2023                2 weeks          5.0
5     01/05/2023                2 weeks          1.0
6     03/04/2023                2 weeks          6.0
7     03/04/2023                2 weeks          7.0
8     16/04/2023                2 weeks          7.0
9     24/04/2023                2 weeks          2.0
10    27/04/2023                2 weeks          8.0
11    01/05/2023                2 weeks          1.0
12    05/05/2023                2 weeks          2.0
13    07/05/2023                2 weeks          3.0
14    10/05/2023                2 weeks          9.0
15    01/06/2023                2 weeks          2.0
16    04/06/2023                2 weeks          3.0
17    07/06/2023                2 weeks          5.0
18    10/07/2023                2 weeks         10.0
19    20/06/2023                2 weeks          2.0  >

In [47]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [51]:
books['Book checkout'] = pd.to_datetime(
    books['Book checkout'].str.strip('"'),
    dayfirst=True,
    errors='coerce')

C:\Users\Admin\AppData\Local\Temp\ipykernel_7364\4154754968.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Book checkout'] = pd.to_datetime(

In [52]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,25/03/2023,2 weeks,3.0
3,4.0,The hobbit,2023-04-02,25/03/2023,2 weeks,4.0
4,5.0,Dune,2023-04-02,25/03/2023,2 weeks,5.0

In [53]:
books['Book Returned'] = pd.to_datetime(
    books['Book Returned'].str.strip('"'),
    dayfirst=True,
    errors='coerce')

C:\Users\Admin\AppData\Local\Temp\ipykernel_7364\2856880438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Book Returned'] = pd.to_datetime(

In [54]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0

In [56]:
books['Days allowed to borrow'] = (
    books['Days allowed to borrow']
    .astype(str)
    .str.extract(r'(\d+(?:\.\d+)?)')[0]
)
books['Days allowed to borrow'] = pd.to_numeric(
    books['Days allowed to borrow'],
   errors='coerce' 
) * 7

C:\Users\Admin\AppData\Local\Temp\ipykernel_7364\2433613532.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Days allowed to borrow'] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_7364\2433613532.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Days allowed to borrow'] = pd.to_numeric(

In [57]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,14,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,14,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,14,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,14,4.0
4,5.0,Dune,2023-04-02,2023-03-25,14,5.0

In [59]:
books.to_csv("Data/03_Library Systembook_clean.csv, index=False")

In [60]:
# calculate the difference between checkout and return

def calculate_days_difference(row):
    return (row['Book Returned'] - row['Book checkout']).days
books['Days Borrowed'] = books.apply(calculate_days_difference, axis=1)
books.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_7364\727830314.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Days Borrowed'] = books.apply(calculate_days_difference, axis=1)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Days Borrowed
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,14,1.0,5.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,14,2.0,-3.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,14,3.0,-4.0
3,4.0,The hobbit,2023-04-02,2023-03-25,14,4.0,-8.0
4,5.0,Dune,2023-04-02,2023-03-25,14,5.0,-8.0

In [62]:
books['Overdue'] = books['Days Borrowed'].apply(
    lambda x: 'Overdue' if x > 14 else 'On time'
)
books.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_7364\2646886661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Overdue'] = books['Days Borrowed'].apply(

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Days Borrowed,Overdue
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,14,1.0,5.0,On time
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,14,2.0,-3.0,On time
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,14,3.0,-4.0,On time
3,4.0,The hobbit,2023-04-02,2023-03-25,14,4.0,-8.0,On time
4,5.0,Dune,2023-04-02,2023-03-25,14,5.0,-8.0,On time

In [63]:
books.to_csv("Data/03_Library Systembook_cleaner.csv, index=False")